### ISSUE TITLE
Skyland AIO-34179-3-0-1649567546 is no longer available on Nexus Mods 

### ISSUE THREAD

**Issue by uranium210** [CritLoren/Yggdrasil-VR#71]
Also, cannot manually download the archived version of Skyland that is referenced here. 

https://www.nexusmods.com/skyrimspecialedition/mods/34179?tab=files&file_id=276070

00:00:26.570 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:00:26.570 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Skyland AIO-34179-3-0-1649567546.7z
00:00:26.979 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0.022888 - Remaining Limit: 8572
00:00:27.242 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0.058244 - Remaining Limit: 8572
00:00:27.242 [INFO] (Wabbajack.Downloaders.NexusDownloader) Downloading Nexus File: SkyrimSpecialEdition|34179|276070
00:00:28.042 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Skyland AIO-34179-3-0-1649567546.7z|System.IO.IOException: The response ended prematurely, with at least 5830501944 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Wabbajack.Hashing.xxHash64.StreamExtensions.HashingCopy(Stream inputStream, Stream outputStream, CancellationToken token, IJob job) in c:\oss\wabbajack\Wabbajack.Hashing.xxHash64\StreamExtensions.cs:line 75
   at Wabbajack.Networking.Http.SingleThreadedDownloader.Download(HttpRequestMessage message, AbsolutePath outputPath, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Networking.Http\SingleThreadedDownloader.cs:line 49
   at Wabbajack.Networking.Http.SingleThreadedDownloader.Download(HttpRequestMessage message, AbsolutePath outputPath, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Networking.Http\SingleThreadedDownloader.cs:line 49
   at Wabbajack.Networking.Http.SingleThreadedDownloader.Download(HttpRequestMessage message, AbsolutePath outputPath, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Networking.Http\SingleThreadedDownloader.cs:line 49
   at Wabbajack.Downloaders.NexusDownloader.Download(Archive archive, Nexus state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Nexus\NexusDownloader.cs:line 133
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 369

**Comment by CritLoren** [comment]
It is tho, change your prefered CDN on nexus in your user preferences and try again.

**Comment by uranium210** [comment]
> It is tho, change your prefered CDN on nexus in your user preferences and try again.

That did the trick - Must have missed it in the setup tips somewhere... 

Thank you!

**Comment by CritLoren** [comment]
It's because it's not there, I've only seen this reported from two users on the server in the last few days, must be a nexus issue. What option was it set to before by any chance?

**Comment by uranium210** [comment]
It was set to the (I'm assuming) default "CDN" Setting. I adjusted it to the closest option i had, which is Chicago, and it took right off on the next attempt.  

Thanks again - Crazy fast response... lol
